bookers2/config/routes.rb
Rails.application.routes.draw do
  
  get 'books/show'
  get 'books/index'
  devise_for :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root to: 'homes#top'

  resources :books
  resources :users, only: [:index, :show, :edit, :update]
end

bookers2/app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

bookers2/app/models/book.rb
class Book < ApplicationRecord
      belongs_to :user
end

bookers2/app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
         
  has_many :books, dependent: :destroy
  attachment :profile_image 
end

bookers2/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
 
  before_action :configure_permitted_parameters, if: :devise_controller?

  
  def after_sign_in_path_for(resource)
    users_path
  end
  
  def after_sign_up_path_for(resource)
     users_path
  end
  
  private 

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:name])
  end
  
  
end

bookers2/app/controllers/books_controller.rb
class BooksController < ApplicationController
  def show
     @books = Book.find(params[:id])
     @user = User.find(params[:id])
     @book = Book.new
  end

  def index
     @books = Book.all
     @book = Book.new
     @user = current_user
  end
  def create
    @book = Book.new(book_params)
    @book.user_id = current_user.id 
    @book.save
    redirect_to book_path(@book)
  end
  def edit
  end
  def destroy
  end  
  
  private
  
  def user_params
    params.require(:user).permit(:name, :profile_image, :introduction)
  end
  
  def book_params
    params.require(:book).permit(:title, :opinion)
  end
end

bookers2/app/controllers/homes_controller.rb
class HomesController < ApplicationController
  def top
  end
end

bookers2/app/controllers/users_controller.rb
class UsersController < ApplicationController
  def index
    @users = User.all
    @book = Book.new
    @user =  current_user
  end

  def show
    @user =  User.find(params[:id])
    @books = Book.find(params[:id])
    @book = Book.new
  end
  
  def edit
    @user = User.find(params[:id])
  end  
  
  def update
    @user = User.find(params[:id])
    @user.update(user_params)
    redirect_to user_path(@user.id)
  end
  
  
  
  private

  def user_params
    params.require(:user).permit(:name, :profile_image, :introduction)
  end
  
  def book_params
    params.require(:user).permit(:title, :opinion)
  end
end

bookers2/app/helpers/application_helper.rb
module ApplicationHelper
end

bookers2/app/helpers/books_helper.rb
module BooksHelper
end

bookers2/app/helpers/homes_helper.rb
module HomesHelper
end

bookers2/app/helpers/users_helper.rb
module UsersHelper
end

bookers2/app/views/books/_newbook.html.erb
<h1>New book</h1>
<%= form_with model:@book, local:true do |f| %>
<h4>title</h4>
  <%= f.text_field :title %>
<h4>opinion</h4>
  <%= f.text_field :opinion %>
  <%= f.submit 'create book' %>
<% end %>

bookers2/app/views/books/_userinfo.html.erb
<h1>Users info</h1>
<%= attachment_image_tag user, :profile_image, :fill, 100, 100, format: 'jpeg', fallback: "no_image.jpg" %>

<p>name：<%= user.name %></p>
<p>introduction：<%= user.introduction %></p>
<li>
 <%= link_to 'Edit', edit_user_path(user.id) %>
</li>

bookers2/app/views/books/index.html.erb
<%= render 'books/userinfo', user: @user %>
<%= render 'books/newbook', book: @book %>
<% @books.each do |book| %>
  <%= attachment_image_tag @user, :profile_image, :fill, 100, 100, format: 'jpeg', fallback: "no_image.jpg" %>
  <div class="one-post card w-100">
   <%= link_to book_path(book) do %>
    <p class="caption h4"><%= book.title %></p>
   <% end %>
   <p class="caption h4"><%= book.opinion %></p>
  </div>
<% end %>

bookers2/app/views/books/show.html.erb
<%= render 'books/userinfo', user: @user %>
<%= render 'books/newbook', book: @book %>
<h1>Book detail</h1>
<%= attachment_image_tag @user, :profile_image, :fill, 100, 100, format: 'jpeg', fallback: "no_image.jpg" %>

<h3 >
    <%= @user.name%>      
</h3>
<h3 >
    <%= @books.title %>      
</h3>
<h3 >
    <%= @books.opinion%>      
</h3>

bookers2/app/views/homes/top.html.erb
<h1>welcometo<i class="fas fa-book"></i>Bookers!!</h1>
<h4>In<i class="fas fa-book"></i>Bookers,</h4>
<h4>you can share and exchange your opinions , inpressions , and emotions</h4>
<h4>about various books!</h4>

<%= link_to 'Log in', new_user_session_path, class: "btn btn-secondary" %>
<%= link_to 'sign up', new_user_registration_path, class: "btn btn-secondary" %>

bookers2/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Bookers2</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    
    <script src="https://kit.fontawesome.com/e575bfee69.js" crossorigin="anonymous"></script>
  </head>

  <body>
    <header>
    <% if user_signed_in? %>
     <nav class="navbar">
      <div class=container>
      
      
      <%= link_to 'Bookers', root_path %>
      
      <ul>
      <li>
      <%= link_to 'Home', user_path(current_user.id) %>
      </li>
      <li>
      <%= link_to 'Users', users_path %>
      </li>
      <li>
      <%= link_to 'Books', books_path %>
      </li>
      <li>
        <%= link_to "logout", destroy_user_session_path, method: :delete %>
      </li>
      </ul>
      </div>
     </nav>
    <% else %>
      <li>
        <%= link_to "新規登録", new_user_registration_path %>
      </li>
      <li>
        <%= link_to "ログイン", new_user_session_path %>
      </li>
    <% end %>
    </header>
    <%= yield %>
  </body>
</html>

bookers2/app/views/users/edit.html.erb
<h1>User info</h1>
<!-- form_with部分 -->
<%= form_with model: @user, url:user_path, local:true do |f| %>
  <h4>name</h4>
  <%= f.text_field :name %>
  
  
  <%= attachment_image_tag @user, :profile_image, :fill, 60, 60, fallback: "no_image.jpg"%>
  <label for="inputImage">ProfileImage</label>
  <%= f.attachment_field :profile_image, placeholder: "プロフィール画像" %>
  
  <h4>introduction</h4>
  <%= f.text_area :introduction %>
  <%= f.submit 'Update User' %>
<% end %>

bookers2/app/views/users/index.html.erb
<%= render 'books/userinfo', user: @user %>
<%= render 'books/newbook', book: @book %>

<div class="cover-user-index">
  <div class="container">
    <div class="row justify-content-center">
      <h1 class="font-weight-normal mt-5 mb-5">ユーザー一覧</h1>
    </div>
    <div class="row justify-content-center">
      <% @users.each do |user| %>
      <div class="one-post card w-100">
        <p><%= user.name %></p>
        <%= link_to user_path(user) do %>
        <p class="caption h4">show</p>
        <% end %>
      </div>
      <% end %>
    </div>
  </div>
</div>

bookers2/app/views/users/show.html.erb
  
  
    
     
      <%= render 'books/userinfo', user: @user %>
      <%= render 'books/newbook', book: @book %>
     
      
      <h1>Books</h1>
       <%= attachment_image_tag @user, :profile_image, :fill, 100, 100, format: 'jpeg', fallback: "no_image.jpg" %>

       <%= link_to book_path(@books) do %>
        <p class="caption h4"><%= @books.title %> </p>
       <% end %>
       <h3 >
        <%= @books.opinion%>      
       </h3>
       
  